import type { Hours, Resource } from "./types";

/**
 * IMPORTANT (honesty): These are real Santa Clara County organizations, but the
 * availability numbers, hours, and phone lines below are ILLUSTRATIVE SEED DATA for a
 * demonstration. Polaris's contribution is the live VERIFICATION layer on top — it never
 * presents a bed as available without re-confirming it. Surfaced in the UI as well.
 */
export const DATA_NOTICE =
  "Resource availability shown is illustrative seed data; Polaris verifies live before routing anyone.";

// --- tiny builders to keep the hours tables readable ---
function nightly(open: string, close: string, intakeCutoff: string): Hours {
  const day = { open, close, intakeCutoff };
  return { 0: day, 1: day, 2: day, 3: day, 4: day, 5: day, 6: day };
}
function daytime(open: string, close: string): Hours {
  const day = { open, close };
  return { 0: null, 1: day, 2: day, 3: day, 4: day, 5: day, 6: null };
}

export const SEED_RESOURCES: Resource[] = [
  {
    id: "fsh-sj",
    name: "San José Family Shelter",
    type: "shelter",
    address: "692 N King Rd",
    city: "San José",
    zip: "95116",
    lat: 37.3617,
    lng: -121.8403,
    phone: "+14085550111",
    hours: nightly("17:00", "08:00", "21:00"),
    servesFamilies: true,
    familyCapacity: 4,
    genderPolicy: "families",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 35,
    openBeds: 6,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Family units; on-site case management.",
  },
  {
    id: "lifemoves-gth",
    name: "LifeMoves Georgia Travis House",
    type: "shelter",
    address: "260 Commercial St",
    city: "San José",
    zip: "95112",
    lat: 37.3539,
    lng: -121.9012,
    phone: "+14085550122",
    hours: nightly("16:30", "08:00", "20:30"),
    servesFamilies: true,
    familyCapacity: 5,
    genderPolicy: "families",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 50,
    openBeds: 3,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Families with children; meals provided.",
  },
  {
    id: "lifemoves-csi",
    name: "LifeMoves Commercial Street Inn",
    type: "shelter",
    address: "85 Pleasant St",
    city: "San José",
    zip: "95112",
    lat: 37.3556,
    lng: -121.901,
    phone: "+14085550133",
    hours: nightly("17:30", "07:30", "21:00"),
    servesFamilies: true,
    familyCapacity: 2,
    genderPolicy: "women_children",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 38,
    openBeds: 4,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Single women and women with children.",
  },
  {
    id: "homefirst-brc",
    name: "HomeFirst Boccardo Reception Center",
    type: "shelter",
    address: "2011 Little Orchard St",
    city: "San José",
    zip: "95125",
    lat: 37.3076,
    lng: -121.8676,
    phone: "+14085550144",
    hours: nightly("16:00", "07:00", "22:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: true,
    sobrietyRequired: false,
    totalBeds: 250,
    openBeds: 18,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Largest county shelter; pets welcome.",
  },
  {
    id: "homefirst-sunnyvale",
    name: "HomeFirst Sunnyvale Shelter",
    type: "shelter",
    address: "620 E Maude Ave",
    city: "Sunnyvale",
    zip: "94089",
    lat: 37.3897,
    lng: -122.0205,
    phone: "+14085550155",
    hours: nightly("18:00", "07:00", "21:30"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 125,
    openBeds: 22,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Adults; overflow capacity in cold weather.",
  },
  {
    id: "cityteam-sj",
    name: "CityTeam San José",
    type: "shelter",
    address: "1297 N 13th St",
    city: "San José",
    zip: "95112",
    lat: 37.3651,
    lng: -121.8966,
    phone: "+14085550166",
    hours: nightly("17:00", "06:30", "20:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "men",
    adaAccessible: false,
    allowsPets: false,
    sobrietyRequired: true,
    totalBeds: 60,
    openBeds: 9,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Men; recovery program; sobriety required.",
  },
  {
    id: "bill-wilson",
    name: "Bill Wilson Center Youth Shelter",
    type: "shelter",
    address: "3490 The Alameda",
    city: "Santa Clara",
    zip: "95050",
    lat: 37.3565,
    lng: -121.9498,
    phone: "+14085550177",
    hours: nightly("16:00", "09:00", "23:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "youth",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 20,
    openBeds: 5,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Youth ages 12–24.",
  },
  {
    id: "marthas-kitchen",
    name: "Martha's Kitchen",
    type: "food",
    address: "311 Willow St",
    city: "San José",
    zip: "95110",
    lat: 37.3219,
    lng: -121.8835,
    phone: "+14085550188",
    hours: daytime("11:00", "15:00"),
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Free hot meals, no questions asked.",
  },
  {
    id: "dignity-showers",
    name: "Dignity on Wheels (Mobile Showers)",
    type: "shower",
    address: "Roving — East San José",
    city: "San José",
    zip: "95116",
    lat: 37.349,
    lng: -121.857,
    phone: "+14085550199",
    hours: daytime("09:00", "13:00"),
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Showers, laundry, hygiene kits.",
  },
  svc("second-harvest", "Second Harvest Food Bank", "food", "4001 N 1st St", "San José", "95134", 37.4101, -121.9416, daytime("09:00", "17:00"), "Free groceries; no ID needed. Call 2-1-1 for sites."),
  svc("sacred-heart", "Sacred Heart Community Service", "food", "1381 S 1st St", "San José", "95110", 37.3169, -121.8769, daytime("10:00", "15:00"), "Food, clothing, and family support."),
  svc("marthas-meals2", "Loaves & Fishes Family Kitchen", "food", "1500 Alum Rock Ave", "San José", "95116", 37.3496, -121.8456, daytime("11:00", "13:30"), "Free hot lunch daily."),
  svc("cityteam-pantry", "CityTeam Food Pantry", "grocery", "1297 N 13th St", "San José", "95112", 37.3651, -121.8966, daytime("10:00", "16:00"), "Free grocery pantry."),
  svc("sunnyvale-cs", "Sunnyvale Community Services", "grocery", "725 Kifer Rd", "Sunnyvale", "94086", 37.3793, -122.0114, daytime("09:00", "16:00"), "Free groceries + rent help."),
  svc("milpitas-pantry", "Milpitas Food Pantry", "grocery", "1440 S Main St", "Milpitas", "95035", 37.4222, -121.8995, daytime("09:30", "12:30"), "Free groceries for Milpitas residents."),
  svc("valley-hhcp", "Valley Homeless Healthcare Program", "clinic", "2400 Moorpark Ave", "San José", "95128", 37.3128, -121.9266, daytime("08:00", "17:00"), "Free clinic for people without housing."),
  svc("gardner-clinic", "Gardner Health Services", "clinic", "160 E Virginia St", "San José", "95112", 37.3262, -121.8788, daytime("08:00", "17:00"), "Sliding-scale medical + dental."),
  svc("homefirst-dropin", "HomeFirst Day Drop-in Center", "drop_in", "2011 Little Orchard St", "San José", "95125", 37.3076, -121.8676, daytime("08:00", "16:00"), "Showers, mail, phone charging, case help."),
  svc("sunnyvale-warming", "Sunnyvale Warming Center", "warming", "620 E Maude Ave", "Sunnyvale", "94089", 37.3897, -122.0205, nightly("20:00", "06:00", "23:00"), "Cold-weather overnight warming center."),
];

// Compact builder for non-shelter services (food/grocery/shower/clinic/drop-in/warming).
function svc(
  id: string,
  name: string,
  type: Resource["type"],
  address: string,
  city: string,
  zip: string,
  lat: number,
  lng: number,
  hours: Hours,
  notes: string,
): Resource {
  return {
    id, name, type, address, city, zip, lat, lng,
    phone: "+14085550000",
    hours,
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes,
  };
}
