import type { Hours, Resource } from "./types";

/**
 * IMPORTANT (honesty): These are real Santa Clara County organizations, but the
 * availability numbers, hours, and phone lines below are ILLUSTRATIVE SEED DATA for a
 * demonstration. Polaris's contribution is the live VERIFICATION layer on top — it never
 * presents a bed as available without re-confirming it. Surfaced in the UI as well.
 */
export const DATA_NOTICE =
  "Resource availability shown is illustrative seed data; Polaris verifies live before routing anyone.";

// --- tiny builders to keep the hours tables readable ---
function nightly(open: string, close: string, intakeCutoff: string): Hours {
  const day = { open, close, intakeCutoff };
  return { 0: day, 1: day, 2: day, 3: day, 4: day, 5: day, 6: day };
}
function daytime(open: string, close: string): Hours {
  const day = { open, close };
  return { 0: null, 1: day, 2: day, 3: day, 4: day, 5: day, 6: null };
}

export const SEED_RESOURCES: Resource[] = [
  {
    id: "fsh-sj",
    name: "San José Family Shelter",
    type: "shelter",
    address: "692 N King Rd",
    city: "San José",
    zip: "95116",
    lat: 37.3617,
    lng: -121.8403,
    phone: "+14085550111",
    hours: nightly("17:00", "08:00", "21:00"),
    servesFamilies: true,
    familyCapacity: 4,
    genderPolicy: "families",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 35,
    openBeds: 6,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Family units; on-site case management.",
  },
  {
    id: "lifemoves-gth",
    name: "LifeMoves Georgia Travis House",
    type: "shelter",
    address: "260 Commercial St",
    city: "San José",
    zip: "95112",
    lat: 37.3539,
    lng: -121.9012,
    phone: "+14085550122",
    hours: nightly("16:30", "08:00", "20:30"),
    servesFamilies: true,
    familyCapacity: 5,
    genderPolicy: "families",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 50,
    openBeds: 3,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Families with children; meals provided.",
  },
  {
    id: "lifemoves-csi",
    name: "LifeMoves Commercial Street Inn",
    type: "shelter",
    address: "85 Pleasant St",
    city: "San José",
    zip: "95112",
    lat: 37.3556,
    lng: -121.901,
    phone: "+14085550133",
    hours: nightly("17:30", "07:30", "21:00"),
    servesFamilies: true,
    familyCapacity: 2,
    genderPolicy: "women_children",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 38,
    openBeds: 4,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Single women and women with children.",
  },
  {
    id: "homefirst-brc",
    name: "HomeFirst Boccardo Reception Center",
    type: "shelter",
    address: "2011 Little Orchard St",
    city: "San José",
    zip: "95125",
    lat: 37.3076,
    lng: -121.8676,
    phone: "+14085550144",
    hours: nightly("16:00", "07:00", "22:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: true,
    sobrietyRequired: false,
    totalBeds: 250,
    openBeds: 18,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Largest county shelter; pets welcome.",
  },
  {
    id: "homefirst-sunnyvale",
    name: "HomeFirst Sunnyvale Shelter",
    type: "shelter",
    address: "620 E Maude Ave",
    city: "Sunnyvale",
    zip: "94089",
    lat: 37.3897,
    lng: -122.0205,
    phone: "+14085550155",
    hours: nightly("18:00", "07:00", "21:30"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 125,
    openBeds: 22,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Adults; overflow capacity in cold weather.",
  },
  {
    id: "cityteam-sj",
    name: "CityTeam San José",
    type: "shelter",
    address: "1297 N 13th St",
    city: "San José",
    zip: "95112",
    lat: 37.3651,
    lng: -121.8966,
    phone: "+14085550166",
    hours: nightly("17:00", "06:30", "20:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "men",
    adaAccessible: false,
    allowsPets: false,
    sobrietyRequired: true,
    totalBeds: 60,
    openBeds: 9,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Men; recovery program; sobriety required.",
  },
  {
    id: "bill-wilson",
    name: "Bill Wilson Center Youth Shelter",
    type: "shelter",
    address: "3490 The Alameda",
    city: "Santa Clara",
    zip: "95050",
    lat: 37.3565,
    lng: -121.9498,
    phone: "+14085550177",
    hours: nightly("16:00", "09:00", "23:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "youth",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 20,
    openBeds: 5,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Youth ages 12–24.",
  },
  {
    id: "marthas-kitchen",
    name: "Martha's Kitchen",
    type: "food",
    address: "311 Willow St",
    city: "San José",
    zip: "95110",
    lat: 37.3219,
    lng: -121.8835,
    phone: "+14085550188",
    hours: daytime("11:00", "15:00"),
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Free hot meals, no questions asked.",
  },
  {
    id: "dignity-showers",
    name: "Dignity on Wheels (Mobile Showers)",
    type: "shower",
    address: "Roving — East San José",
    city: "San José",
    zip: "95116",
    lat: 37.349,
    lng: -121.857,
    phone: "+14085550199",
    hours: daytime("09:00", "13:00"),
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Showers, laundry, hygiene kits.",
  },
];
