import type { Hours, Resource } from "./types";

/**
 * IMPORTANT (honesty): These are real Santa Clara County organizations, but the
 * availability numbers, hours, and phone lines below are ILLUSTRATIVE SEED DATA for a
 * demonstration. Polaris's contribution is the live VERIFICATION layer on top — it never
 * presents a bed as available without re-confirming it. Surfaced in the UI as well.
 */
export const DATA_NOTICE =
  "Resource availability shown is illustrative seed data; Polaris verifies live before routing anyone.";

// --- tiny builders to keep the hours tables readable ---
function nightly(open: string, close: string, intakeCutoff: string): Hours {
  const day = { open, close, intakeCutoff };
  return { 0: day, 1: day, 2: day, 3: day, 4: day, 5: day, 6: day };
}
function daytime(open: string, close: string): Hours {
  const day = { open, close };
  return { 0: null, 1: day, 2: day, 3: day, 4: day, 5: day, 6: null };
}

export const SEED_RESOURCES: Resource[] = [
  {
    id: "fsh-sj",
    name: "San José Family Shelter",
    type: "shelter",
    address: "692 N King Rd",
    city: "San José",
    zip: "95116",
    lat: 37.3617,
    lng: -121.8403,
    phone: "+14085550111",
    hours: nightly("17:00", "08:00", "21:00"),
    servesFamilies: true,
    familyCapacity: 4,
    genderPolicy: "families",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 35,
    openBeds: 6,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Family units; on-site case management.",
  },
  {
    id: "lifemoves-gth",
    name: "LifeMoves Georgia Travis House",
    type: "shelter",
    address: "260 Commercial St",
    city: "San José",
    zip: "95112",
    lat: 37.3539,
    lng: -121.9012,
    phone: "+14085550122",
    hours: nightly("16:30", "08:00", "20:30"),
    servesFamilies: true,
    familyCapacity: 5,
    genderPolicy: "families",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 50,
    openBeds: 3,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Families with children; meals provided.",
  },
  {
    id: "lifemoves-csi",
    name: "LifeMoves Commercial Street Inn",
    type: "shelter",
    address: "85 Pleasant St",
    city: "San José",
    zip: "95112",
    lat: 37.3556,
    lng: -121.901,
    phone: "+14085550133",
    hours: nightly("17:30", "07:30", "21:00"),
    servesFamilies: true,
    familyCapacity: 2,
    genderPolicy: "women_children",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 38,
    openBeds: 4,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Single women and women with children.",
  },
  {
    id: "homefirst-brc",
    name: "HomeFirst Boccardo Reception Center",
    type: "shelter",
    address: "2011 Little Orchard St",
    city: "San José",
    zip: "95125",
    lat: 37.3076,
    lng: -121.8676,
    phone: "+14085550144",
    hours: nightly("16:00", "07:00", "22:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: true,
    sobrietyRequired: false,
    totalBeds: 250,
    openBeds: 18,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Largest county shelter; pets welcome.",
  },
  {
    id: "homefirst-sunnyvale",
    name: "HomeFirst Sunnyvale Shelter",
    type: "shelter",
    address: "620 E Maude Ave",
    city: "Sunnyvale",
    zip: "94089",
    lat: 37.3897,
    lng: -122.0205,
    phone: "+14085550155",
    hours: nightly("18:00", "07:00", "21:30"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 125,
    openBeds: 22,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Adults; overflow capacity in cold weather.",
  },
  {
    id: "cityteam-sj",
    name: "CityTeam San José",
    type: "shelter",
    address: "1297 N 13th St",
    city: "San José",
    zip: "95112",
    lat: 37.3651,
    lng: -121.8966,
    phone: "+14085550166",
    hours: nightly("17:00", "06:30", "20:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "men",
    adaAccessible: false,
    allowsPets: false,
    sobrietyRequired: true,
    totalBeds: 60,
    openBeds: 9,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Men; recovery program; sobriety required.",
  },
  {
    id: "bill-wilson",
    name: "Bill Wilson Center Youth Shelter",
    type: "shelter",
    address: "3490 The Alameda",
    city: "Santa Clara",
    zip: "95050",
    lat: 37.3565,
    lng: -121.9498,
    phone: "+14085550177",
    hours: nightly("16:00", "09:00", "23:00"),
    servesFamilies: false,
    familyCapacity: 0,
    genderPolicy: "youth",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 20,
    openBeds: 5,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Youth ages 12–24.",
  },
  {
    id: "marthas-kitchen",
    name: "Martha's Kitchen",
    type: "food",
    address: "311 Willow St",
    city: "San José",
    zip: "95110",
    lat: 37.3219,
    lng: -121.8835,
    phone: "+14085550188",
    hours: daytime("11:00", "15:00"),
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Free hot meals, no questions asked.",
  },
  {
    id: "dignity-showers",
    name: "Dignity on Wheels (Mobile Showers)",
    type: "shower",
    address: "Roving — East San José",
    city: "San José",
    zip: "95116",
    lat: 37.349,
    lng: -121.857,
    phone: "+14085550199",
    hours: daytime("09:00", "13:00"),
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: "Showers, laundry, hygiene kits.",
  },
  svc("second-harvest", "Second Harvest Food Bank", "food", "4001 N 1st St", "San José", "95134", 37.4101, -121.9416, daytime("09:00", "17:00"), "Free groceries; no ID needed. Call 2-1-1 for sites."),
  svc("sacred-heart", "Sacred Heart Community Service", "food", "1381 S 1st St", "San José", "95110", 37.3169, -121.8769, daytime("10:00", "15:00"), "Food, clothing, and family support."),
  svc("marthas-meals2", "Loaves & Fishes Family Kitchen", "food", "1500 Alum Rock Ave", "San José", "95116", 37.3496, -121.8456, daytime("11:00", "13:30"), "Free hot lunch daily."),
  svc("cityteam-pantry", "CityTeam Food Pantry", "grocery", "1297 N 13th St", "San José", "95112", 37.3651, -121.8966, daytime("10:00", "16:00"), "Free grocery pantry."),
  svc("sunnyvale-cs", "Sunnyvale Community Services", "grocery", "725 Kifer Rd", "Sunnyvale", "94086", 37.3793, -122.0114, daytime("09:00", "16:00"), "Free groceries + rent help."),
  svc("milpitas-pantry", "Milpitas Food Pantry", "grocery", "1440 S Main St", "Milpitas", "95035", 37.4222, -121.8995, daytime("09:30", "12:30"), "Free groceries for Milpitas residents."),
  svc("valley-hhcp", "Valley Homeless Healthcare Program", "clinic", "2400 Moorpark Ave", "San José", "95128", 37.3128, -121.9266, daytime("08:00", "17:00"), "Free clinic for people without housing."),
  svc("gardner-clinic", "Gardner Health Services", "clinic", "160 E Virginia St", "San José", "95112", 37.3262, -121.8788, daytime("08:00", "17:00"), "Sliding-scale medical + dental."),
  svc("homefirst-dropin", "HomeFirst Day Drop-in Center", "drop_in", "2011 Little Orchard St", "San José", "95125", 37.3076, -121.8676, daytime("08:00", "16:00"), "Showers, mail, phone charging, case help."),
  svc("sunnyvale-warming", "Sunnyvale Warming Center", "warming", "620 E Maude Ave", "Sunnyvale", "94089", 37.3897, -122.0205, nightly("20:00", "06:00", "23:00"), "Cold-weather overnight warming center."),

  // ---- more shelters (Milpitas / San José / nearby) ----
  shelter("salvation-emmanuel", "Salvation Army Emmanuel House", "405 N 4th St", "San José", "95112", 37.353, -121.892, 60, 7, "men", { sobriety: true, notes: "Men's residential recovery program." }),
  shelter("lifemoves-montgomery", "LifeMoves Montgomery Street Inn", "358 N Montgomery St", "San José", "95110", 37.334, -121.901, 90, 5, "men", { notes: "Men 18+; on-site case management." }),
  shelter("faith-in-action", "Faith in Action Rotating Shelter", "Rotating congregations", "San José", "95112", 37.349, -121.88, 15, 4, "any", { families: true, famCap: 3, notes: "Rotating congregational shelter." }),
  shelter("milpitas-cws", "Milpitas Cold Weather Shelter", "1325 E Calaveras Blvd", "Milpitas", "95035", 37.428, -121.887, 40, 9, "any", { notes: "Seasonal overflow shelter." }),
  shelter("lifemoves-mtnview", "LifeMoves Mountain View", "2566 Leghorn St", "Mountain View", "94043", 37.418, -122.093, 100, 8, "families", { families: true, famCap: 5, notes: "Family shelter + housing services." }),
  shelter("bill-wilson-family", "Bill Wilson Family Living Center", "693 S 2nd St", "San José", "95112", 37.328, -121.882, 30, 6, "families", { families: true, famCap: 4, ada: true, notes: "Families with children." }),

  // ---- food, groceries, meals ----
  svc("cathedral-breakfast", "St. Joseph's Cathedral Breakfast", "food", "80 S Market St", "San José", "95113", 37.3354, -121.891, daytime("07:00", "08:30"), "Free breakfast, no questions asked."),
  svc("cityteam-meals", "CityTeam Free Meals", "food", "1297 N 13th St", "San José", "95112", 37.3651, -121.8966, daytime("11:30", "12:30"), "Free hot lunch daily."),
  svc("sunnyvale-meals", "Sunnyvale Community Dinner", "food", "725 Kifer Rd", "Sunnyvale", "94086", 37.3793, -122.0114, daytime("18:00", "19:00"), "Free community dinner."),
  svc("berryessa-pantry", "Berryessa Food Pantry", "grocery", "3050 Berryessa Rd", "San José", "95132", 37.379, -121.859, daytime("09:00", "11:00"), "Neighborhood grocery pantry."),
  svc("eastside-center", "Eastside Neighborhood Center", "grocery", "2150 Alum Rock Ave", "San José", "95116", 37.37, -121.835, daytime("09:00", "16:00"), "Food + family services."),
  svc("west-valley-cs", "West Valley Community Services", "grocery", "10104 Vista Dr", "Cupertino", "95014", 37.323, -122.009, daytime("10:00", "16:00"), "Free groceries + case management."),
  svc("gardner-pantry", "Gardner Family Health Pantry", "grocery", "160 E Virginia St", "San José", "95112", 37.3262, -121.8788, daytime("09:00", "12:00"), "Food pantry for patients + neighbors."),
  svc("salvation-pantry", "Salvation Army Food Pantry", "grocery", "359 N 4th St", "San José", "95112", 37.3525, -121.8918, daytime("09:00", "12:00"), "Free grocery pantry."),

  // ---- showers, hygiene, clinics ----
  svc("dignity-sj", "Dignity on Wheels — San José", "shower", "Roving (downtown)", "San José", "95110", 37.328, -121.89, daytime("09:00", "13:00"), "Mobile showers + laundry."),
  svc("fcc-showers", "First Christian Church Showers", "shower", "80 S 5th St", "San José", "95112", 37.337, -121.883, daytime("08:00", "11:00"), "Free showers + hygiene kits."),
  svc("indian-health", "Indian Health Center", "clinic", "1333 Meridian Ave", "San José", "95125", 37.305, -121.901, daytime("08:00", "17:00"), "Medical + dental; everyone welcome."),
  svc("foothill-chc", "Foothill Community Health Center", "clinic", "2585 Samaritan Dr", "San José", "95124", 37.257, -121.943, daytime("08:00", "17:00"), "Sliding-scale clinic."),
  svc("school-health", "School Health Clinics", "clinic", "976 Lenzen Ave", "San José", "95126", 37.336, -121.912, daytime("08:00", "17:00"), "Low-cost medical care."),

  // ---- warm spaces, charging, drop-in ----
  svc("mlk-library", "Dr. MLK Jr. Library", "warming", "150 E San Fernando St", "San José", "95112", 37.3358, -121.885, daytime("10:00", "20:00"), "Warm space, charging, restrooms, wifi."),
  svc("milpitas-library", "Milpitas Public Library", "warming", "160 N Main St", "Milpitas", "95035", 37.429, -121.907, daytime("10:00", "18:00"), "Warm space, charging, wifi."),
  svc("sunnyvale-library", "Sunnyvale Public Library", "warming", "665 W Olive Ave", "Sunnyvale", "94086", 37.378, -122.038, daytime("10:00", "18:00"), "Warm space, charging, wifi."),
  svc("defrank-center", "Billy DeFrank LGBTQ+ Center", "drop_in", "938 The Alameda", "San José", "95126", 37.334, -121.908, daytime("12:00", "18:00"), "Drop-in, resources, community."),
  svc("sacred-heart-closet", "Sacred Heart Clothes Closet", "drop_in", "1381 S 1st St", "San José", "95110", 37.3169, -121.8769, daytime("10:00", "15:00"), "Free clothing + hygiene."),
];

// Compact builder for non-shelter services (food/grocery/shower/clinic/drop-in/warming).
function svc(
  id: string,
  name: string,
  type: Resource["type"],
  address: string,
  city: string,
  zip: string,
  lat: number,
  lng: number,
  hours: Hours,
  notes: string,
): Resource {
  return {
    id, name, type, address, city, zip, lat, lng,
    phone: "+14085550000",
    hours,
    servesFamilies: true,
    familyCapacity: 0,
    genderPolicy: "any",
    adaAccessible: true,
    allowsPets: false,
    sobrietyRequired: false,
    totalBeds: 0,
    openBeds: 0,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes,
  };
}

// Compact builder for shelters (overnight beds). Defaults to ADA-accessible, 9 PM intake cutoff.
function shelter(
  id: string,
  name: string,
  address: string,
  city: string,
  zip: string,
  lat: number,
  lng: number,
  totalBeds: number,
  openBeds: number,
  genderPolicy: Resource["genderPolicy"],
  opts: { families?: boolean; famCap?: number; ada?: boolean; pets?: boolean; sobriety?: boolean; cutoff?: string; notes?: string } = {},
): Resource {
  return {
    id, name, type: "shelter", address, city, zip, lat, lng,
    phone: "+14085550000",
    hours: nightly("17:00", "08:00", opts.cutoff ?? "21:00"),
    servesFamilies: opts.families ?? false,
    familyCapacity: opts.famCap ?? 0,
    genderPolicy,
    adaAccessible: opts.ada ?? true,
    allowsPets: opts.pets ?? false,
    sobrietyRequired: opts.sobriety ?? false,
    totalBeds,
    openBeds,
    lastVerifiedAt: null,
    verifyMethod: "seed",
    notes: opts.notes ?? "",
  };
}
